import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  overlayContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  dismissOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  searchCard: {
    marginHorizontal: 12,
    backgroundColor: "#fff",
    borderRadius: 22,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 6,
  },
  searchRow: {
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  searchLabel: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  originLabel: {
    color: "#2563EB",
  },
  destinationLabel: {
    color: "#F97316",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F3F4F6",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputIcon: {
    width: 20,
    alignItems: "center",
  },
  searchInput: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
    paddingVertical: 0,
    paddingHorizontal: 0,
    flex: 1,
  },
  clearButton: {
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  rowActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  suggestionsContainer: {
    maxHeight: 260,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  suggestionsHint: {
    color: "#6B7280",
    fontSize: 12,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  suggestionItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  suggestionText: {
    color: "#111827",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  suggestionSubtext: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
  },
  suggestionSeparator: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginLeft: 14,
    marginRight: 14,
  },
  markerDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "rgba(37, 99, 235, 0.25)",
    borderWidth: 2,
    borderColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
  },
  markerDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#2563EB",
  },
  markerPin: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(220, 38, 38, 0.25)",
    borderWidth: 2,
    borderColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
  },
  markerPinInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#DC2626",
  },
  banner: {
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 10,
    marginHorizontal: 12,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 4,
  },
  bannerTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  bannerBody: {
    color: "#374151",
    fontSize: 13,
    marginTop: 4,
    opacity: 0.9,
  },
  routeSummaryCard: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    marginHorizontal: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderRadius: 24,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 6,
  },
  routeSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  routeSummaryLabel: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  routeSummaryValue: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  routeSummaryDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 12,
  },
  floatingActionButton: {
    position: "absolute",
    right: 12,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 6,
  },
  quickActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  belowCardActions: {
    marginTop: 10,
    marginHorizontal: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  belowCardIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 4,
  },
  bannerActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  button: {
    backgroundColor: "#2563EB",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  buttonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
  },
  buttonSecondary: {
    backgroundColor: "rgba(17, 24, 39, 0.06)",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  buttonSecondaryText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "600",
  },
  title: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 48,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  body: {
    fontSize: 14,
    lineHeight: 20,
    marginHorizontal: 16,
  },
});
